name: deploy
on: 
    push:
        branches:
            -   desenvolvimento

    pull_request: 
        branches:
            -   desenvolvimento

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout code
                uses: actions/checkout@v4

            -   name: setup node v20
                uses: actions/setup-node@v3
                with:
                    node-version: '20'
                    
            -   name: install node dependencies
                run: npm install
            
            -   name: testing
                run:  npm test

            -   name: install gh-pages
                run: npm install -D gh-pages

            -   name: set git username and email
                run: |
                    git config --global user.email "${{github.actor}}@users.noreply.github.com"
                    git config --global user.name "${{github.actor}}"

            -   name: run deploy
                run: npm run deploy