name: test-dev
on: 
    push:
        branches:
            -   desenvolvimento

    pull_request: 
        branches:
            -   desenvolvimento

jobs:
    test-dev:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout code
                uses: actions/checkout@v4

            -   name: setup node v20
                uses: actions/setup-node@v3
                with:
                    node-version: '20'
                    
            -   name: install dependencies and run test
                run: |
                    npm install
                    npm test
            -   name: Create PR to branch
                uses: gorillio/github-action-cherry-pick@master
                with:
                    pr_branch: 'homologação'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GITBOT_EMAIL: <BOT_EMAIL>
                    DRY_RUN: false